YUNIKORN-1557: expose build info in webapp
apache/yunikorn-web pull request #111
Opened 2023-05-09 03:16 UTC by lixmgl

### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1557
* Put link here, and add [YUNIKORN-1557] in PR title, eg. `expose build info in webapp`

### How should this be tested?
tested locally

### Screenshots (if appropriate)
<img width="1672" alt="Screenshot 2023-05-08 at 8 09 11 PM" src="https://user-images.githubusercontent.com/7441350/236984975-cd14906a-42e7-4b59-8841-624a2176f969.png">

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2023-05-09 06:12 UTC, 0yukali0 requested changes
Almost done in my viewpoint.
BTW, i cloned this PR to run the web locally successfully.
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/45888688/237009572-5ec222fe-a4d3-46f4-8f84-018fd9378251.png">

2023-05-09 15:19 UTC, lixmgl commented on src/app/models/cluster-info.model.ts
> +}
@0yukali0 thanks for reviewing the pr, I added a new line.

2023-05-09 17:03 UTC, craigcondit requested changes
I think it would be best to put that info under the Help (?) menu. It makes the main UI very cluttered, and requires a quite-wide browser window to display properly.

2023-05-09 18:40 UTC, lixmgl commented
> 



> I think it would be best to put that info under the Help (?) menu. It makes the main UI very cluttered, and requires a quite-wide browser window to display properly.

@craigcondit I don't think ? menu is the best approach since buildInfo is part of ClusterInfo. I adjust the format to include buildInfo in a new column (please check screenshot #3), this approach addressed quite-wide browser issue. Later we can add more buildInfo into this column.

2023-05-09 18:48 UTC, craigcondit commented
> I don't think ? menu is the best approach since buildInfo is part of ClusterInfo. I adjust the format to include buildInfo in a new column (please check screenshot #3), this approach addressed quite-wide browser issue. Later we can add more buildInfo into this column.

It's still information that is only really needed for debugging, not day-to-day use. Most users of the UI are not going to care what build ID or date or whatever are present in the metadata. But an about page that lists information such as this would be helpful. The fact that the REST API returns this as part of ClusterInfo isn't really relevant -- the UI doesn't need to organize the information the same way.

2023-05-10 00:57 UTC, lixmgl commented
> 



> > I don't think ? menu is the best approach since buildInfo is part of ClusterInfo. I adjust the format to include buildInfo in a new column (please check screenshot #3), this approach addressed quite-wide browser issue. Later we can add more buildInfo into this column.
> 
> It's still information that is only really needed for debugging, not day-to-day use. Most users of the UI are not going to care what build ID or date or whatever are present in the metadata. But an about page that lists information such as this would be helpful. The fact that the REST API returns this as part of ClusterInfo isn't really relevant -- the UI doesn't need to organize the information the same way.

That make sense @craigcondit 
I created a new Info card for Build related info (Please check screenshot #4 & 5)

> > I don't think ? menu is the best approach since buildInfo is part of ClusterInfo. I adjust the format to include buildInfo in a new column (please check screenshot #3), this approach addressed quite-wide browser issue. Later we can add more buildInfo into this column.
> 
> It's still information that is only really needed for debugging, not day-to-day use. Most users of the UI are not going to care what build ID or date or whatever are present in the metadata. But an about page that lists information such as this would be helpful. The fact that the REST API returns this as part of ClusterInfo isn't really relevant -- the UI doesn't need to organize the information the same way.

Good point @craigcondit, I moved build related info into a new Info card. 
Please check screenshot. If you click on the icon, it will display all build info.

2023-05-10 01:46 UTC, wilfred-s commented
I like the use and location of the info card, I think that is also an extensible setup. We are looking at adding more details to the build info and that card can easily expand with further details.

Not sure why the unit tests are failing, not really a js developer...

2023-05-10 03:08 UTC, lixmgl commented
> I like the use and location of the info card, I think that is also an extensible setup. We are looking at adding more details to the build info and that card can easily expand with further details.
> 
> Not sure why the unit tests are failing, not really a js developer...

I just fixed the unit tests. 
Right, i will add more buildInfo after backend changes are landed. Tracking ticket: [YUNIKORN-1727](https://issues.apache.org/jira/browse/YUNIKORN-1727)

2023-05-10 15:31 UTC, craigcondit reviewed
+1 LGTM.

2023-05-10 15:32 UTC, closed without merging