[YUNIKORN-2342] Skeleton of the new UI
apache/yunikorn-web pull request #177
Opened 2024-03-08 13:41 UTC by doupache

### What is this PR for?
Queue UI v2 

### What type of PR is it?
* [ ] - Feature

### What is the Jira issue?
[YUNIKORN-2342](https://issues.apache.org/jira/browse/YUNIKORN-2342)
[YUNIKORN-2343](https://issues.apache.org/jira/browse/YUNIKORN-2343)
[YUNIKORN-2345](https://issues.apache.org/jira/browse/YUNIKORN-2345)
[YUNIKORN-2346](https://issues.apache.org/jira/browse/YUNIKORN-2346)
[YUNIKORN-2348](https://issues.apache.org/jira/browse/YUNIKORN-2348)

### Screenshots (if appropriate)

2024-03-08 13:57 UTC, doupache commented
cc @craigcondit @wilfred-s

2024-03-20 00:19 UTC, wilfred-s commented
With the move to pnpm changes are needed. I got this to compile with the [attached patch](https://github.com/apache/yunikorn-web/files/14658131/pnpm_update.patch) using pnpm so all looks good from that side. If you can make the change to resolve the conflicts we are ready to commit.

2024-03-20 23:06 UTC, doupache commented
Thanks @wilfred-s 
I switched this branch to `pnpm` by running the following command

```
1. git merge master 
2. make clean 
3. pnpm install 
4. make start-dev
```
Everything worked smoothly. 
I think it is ready to go 🎉

2024-03-21 21:11 UTC, craigcondit approved these changes
+1 LGTM.

2024-03-22 04:50 UTC, chenyulin0719 requested changes
1 change required.

2024-03-22 04:50 UTC, chenyulin0719 commented on src/app/components/queue-v2/queues-v2.component.ts
> +    let partitionName = 'defau';
Should be 'default'.

2024-03-22 04:50 UTC, chenyulin0719 commented on src/app/components/queue-v2/queues-v2.component.spec.ts
> +      expect(schedulerSpy).toHaveBeenCalledWith('defau');
ditto

2024-03-22 04:50 UTC, chenyulin0719 commented on src/app/components/queue-v2/queues-v2.component.ts
> +    let partitionName = 'defau';
<img width="1385" alt="image" src="https://github.com/apache/yunikorn-web/assets/26764036/80cbac96-5787-4c1b-af72-0b35203e9368">

2024-03-29 12:48 UTC, doupache commented
Thank you, @chenyulin0719, for the review.
I've also tested the web UI with the actual API.  
Everything works!

Please take a look.

2024-04-01 15:27 UTC, chenyulin0719 approved these changes
+1 LGTM

2024-04-05 15:10 UTC, closed without merging

2024-04-06 00:15 UTC, doupache commented
Thanks everyone for the help !