[YUNIKORN-2829] Improve table layout for Applications
apache/yunikorn-web pull request #214
Opened 2024-10-21 09:06 UTC by blueBlue0102

### What is this PR for?
Improve table layout for Applications.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
[YUNIKORN-2829](https://issues.apache.org/jira/browse/YUNIKORN-2829)

### How should this be tested?

### Screenshots (if appropriate)
**Before:**
![before](https://github.com/user-attachments/assets/5455dd5b-821f-4fe9-a2d2-1a495d9b2c28)

**After:**
![after](https://github.com/user-attachments/assets/509cd758-9414-4941-a68c-d3d79f3e7a73)

2024-10-22 21:14 UTC, craigcondit requested changes
We should still center the column values (as the headers already are).

2024-10-25 08:35 UTC, blueBlue0102 commented
Is this what you had in mind?

![text-align center 0](https://github.com/user-attachments/assets/3219d127-e8fa-473b-8952-e1f18e91ce5a)
![text-align center](https://github.com/user-attachments/assets/2a906434-ea42-414d-8bd4-8552ee05e56f)
![text-align center 2](https://github.com/user-attachments/assets/382bc05b-c185-4ef8-a976-2d1994a4118d)

or this one:
![0](https://github.com/user-attachments/assets/f9c2dde4-3227-42bd-97da-ec011c62c8f4)
![1](https://github.com/user-attachments/assets/d971b863-3e0c-4fc2-9396-1b65c5a746b4)
![2](https://github.com/user-attachments/assets/5a3ae019-6ada-408a-b9e2-35c3f2728b27)

2024-10-25 20:36 UTC, craigcondit commented
> Is this what you had in mind?

Neither. Simply ensure that each cell has the same justification (left for column 1, centered for others). There are strange offsets that look out of place in every example you've shown so far.

2024-10-26 02:44 UTC, blueBlue0102 commented
Before this PR, all the values were left-aligned in every column.
![任何修改以前67%](https://github.com/user-attachments/assets/af4a465d-7a13-4850-8ec2-15b368cbafd0)
![任何修改以前100%](https://github.com/user-attachments/assets/14ca3302-dc1e-426b-88a6-2c8c093d6893)
![任何修改以前125%](https://github.com/user-attachments/assets/7207a2ad-0514-4c1a-a00e-f725bbb0dd8f)
![任何修改以前](https://github.com/user-attachments/assets/1b82891d-1e6c-4f45-a17a-8d276c639b0f)

I can fix the alignment to match what you suggested - left for the first column and centered for the rest.

2024-11-01 04:09 UTC, chenyulin0719 commented
Hi @blueBlue0102 , Could you resolve the conflicts?

2024-11-14 03:46 UTC, blueBlue0102 commented
> Before this PR, all the values were left-aligned in every column. ![任何修改以前67%](https://private-user-images.githubusercontent.com/46772690/380356450-af4a465d-7a13-4850-8ec2-15b368cbafd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTYwNzQsIm5iZiI6MTczMTU1NTc3NCwicGF0aCI6Ii80Njc3MjY5MC8zODAzNTY0NTAtYWY0YTQ2NWQtN2ExMy00ODUwLThlYzItMTViMzY4Y2JhZmQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmQ5NTNjNTdhZmI1MThiYjIxMDZmZDRkYTBlYTE4MmUzYzdmOTE3MjQ5MzBhYzgzYmQ3NjE0NGZmOWY2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Moi46kliBf_lRHzA4MQNoKRRMglCCPC-YmP_RZfz6s4) ![任何修改以前100%](https://private-user-images.githubusercontent.com/46772690/380356457-14ca3302-dc1e-426b-88a6-2c8c093d6893.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTYwNzQsIm5iZiI6MTczMTU1NTc3NCwicGF0aCI6Ii80Njc3MjY5MC8zODAzNTY0NTctMTRjYTMzMDItZGMxZS00MjZiLTg4YTYtMmM4YzA5M2Q2ODkzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNjA1ZjY4MTI1OTA0MmI5NzBhMTRlZTMzZDA4MWQ5ZDE5M2ViNjE3MWRiZTM5OWJkMDZjZTk4MGQyNDI4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PwesgdbO_IMCx6hOTGFCb9M0PsIOGS8_5ClvYoE3b0U) ![任何修改以前125%](https://private-user-images.githubusercontent.com/46772690/380356460-7207a2ad-0514-4c1a-a00e-f725bbb0dd8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTYwNzQsIm5iZiI6MTczMTU1NTc3NCwicGF0aCI6Ii80Njc3MjY5MC8zODAzNTY0NjAtNzIwN2EyYWQtMDUxNC00YzFhLWEwMGUtZjcyNWJiYjBkZDhmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzE1MGIxNDBkZDdhZmExNmQ3NzIzOTYzYWM1NmJkZjNlNjJhOTE2N2M2NTI2NGNiOWExYWZkYWY1ZGFlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.11HUxWCPqlERVmCLxeMTft35eSbCAZ9UVusxGtfKcbY) ![任何修改以前](https://private-user-images.githubusercontent.com/46772690/380356464-1b82891d-1e6c-4f45-a17a-8d276c639b0f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTYwNzQsIm5iZiI6MTczMTU1NTc3NCwicGF0aCI6Ii80Njc3MjY5MC8zODAzNTY0NjQtMWI4Mjg5MWQtMWU2Yy00ZjQ1LWExN2EtOGQyNzZjNjM5YjBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZWIxOGVlMWM0OWVhNGU0NzNmYzM0MWM4NWEyODU3YmI0MTJkZWRmZmUwNzY0YmVmNDhiMGFmNDk0ZDgxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hU68lbVyY0YgzZchasfV8jDfd6DJJzI-jrQj4Hqt1Wg)
> 
> I can fix the alignment to match what you suggested - left for the first column and centered for the rest.

Hi @craigcondit, do you have any thoughts on this approach?

2024-11-14 18:51 UTC, craigcondit commented
> > I can fix the alignment to match what you suggested - left for the first column and centered for the rest.
> 
> Hi @craigcondit, do you have any thoughts on this approach?

That should be fine. Please fix the merge conflicts as well.

2024-11-21 20:57 UTC, craigcondit commented
@blueBlue0102 did you mean to revert everything?

2025-02-15 11:39 UTC, blueBlue0102 commented
Rather than setting flex ratio for each column, set max-width to all columns except Application ID. This allows the Application ID column to utilize maximum available space.

![image](https://github.com/user-attachments/assets/85057195-4f71-43f2-a884-f72092a4b7f7)
![image](https://github.com/user-attachments/assets/6d5cfb24-a46f-474a-822e-5335f8d1fb4d)
![image](https://github.com/user-attachments/assets/9d7ed0da-d277-4871-86f3-b8593a21d75a)

2025-02-20 17:59 UTC, craigcondit approved these changes
+1 LGTM.

2025-02-20 17:59 UTC, craigcondit approved these changes
+1 LGTM.

2025-02-20 18:04 UTC, closed without merging